name: unicorn-binance-suite

channels:
  - conda-forge

dependencies:
  - python>=3.9
  - unicorn-fy
  - unicorn-binance-local-depth-cache
  - unicorn-binance-rest-api
  - unicorn-binance-trailing-stop-loss
  - unicorn-binance-websocket-api
